### ISSUE TITLE
redux-persist

### ISSUE THREAD

**Issue by slgarkea** [KevinAst/feature-redux#15]
Hi Kevin,

First, thanks for the work you're doing here !

I'm trying to get redux-persist working along to feature-redux.
My current approch is to wrap feature-redux to a feature-redux-persist aspect but it is not working. Maybe I miss something in the feature-u architecture which allow me to do this more easily ?

The current code : 

```js
import React from 'react'; // peerDependencies
import { extendAspectProperty, createAspect, launchApp } from 'feature-u'; // peerDependency:
import { createReducerAspect } from 'feature-redux';
import { persistStore } from 'redux-persist';
import { PersistGate } from 'redux-persist/integration/react';

import verify from './util/verify';

export const logf = launchApp.diag.logf.newLogger(
  '- ***feature-redux-persist*** reduxPersistAspect: '
);

// TODO tests !
export function createPersistedReducerAspect(name = 'reducer') {
  // validate parameters
  const check = verify.prefix(
    'createPersistedReducerAspect() parameter violation: '
  );

  check(name, 'name is required');
  check(typeof name === 'string', 'name must be a string'); // NOTE: didn't want to introduce lodash.isstring dependancy (in the mix of everything else going on in the 1.0.0 upgrade)

  const reduxAspect = createReducerAspect(name);
  const {
    getReduxStore,
    getReduxMiddleware,
    ...restrictedReduxAspect
  } = reduxAspect;

  return createAspect({
    ...restrictedReduxAspect,
    genesis,
    injectRootAppElm: (fassets, curRootAppElm) => {
      const persistor = persistStore(reduxAspect.getReduxStore());

      return reduxAspect.injectRootAppElm(
        fassets,
        injectRootAppElm(fassets, curRootAppElm, persistor)
      );
    },
  });
}

function genesis() {
  logf(
    'genesis() registering two new Aspect properties: getReduxStore() -and- getReduxMiddleware()'
  );

  // extendAspectProperty('getReduxStore', 'feature-redux-persist'); // Aspect.getReduxStore(): store
  // extendAspectProperty('getReduxMiddleware', 'feature-redux-persist'); // Aspect.getReduxMiddleware(): reduxMiddleware
}

function injectRootAppElm(fassets, curRootAppElm, persistor) {
  if (curRootAppElm) {
    throw new Error(
      '***ERROR*** Please register reduxPersistAspect (from feature-router) after feautre-redux aspect ' +
        'that inject content in the rootAppElm ...'
    );
  }

  return (
    <PersistGate loading={null} persistor={persistor}>
      {curRootAppElm}
    </PersistGate>
  );
}
```

**Comment by KevinAst** [comment]
Hello Sylvain,

I have not used redux-persist.  I did look at the docs briefly, however my time is a bit limited right now :-(

I am unsure of the results you are experiencing.  You say "it is not working" ... is it erroring in some way, or silently no-oping, or something else?

One question: Have you gotten your app to work with plain redux (i.e. without redux-persist)?

Your approach of wrapping is an interesting one.  I assume in this "wrapped" approach you are planning on using the createPersistedReducerAspect() in place of the feature-redux createReducerAspect() ... yes?

I do see a couple of issues with your implementation:

1. Your genesis() method is NOT passing through to feature-redux genesis(), which means we have lost the original feature-redux genesis() functionality.

2. Your injectRootAppElm() method is incorrectly throwing an error when prior children exist (i.e. the curRootAppElm param).  This injection should be able to support children.

3. Relative to redux-persist, I do not see where you are wrapping the top-level app reducer with the redux-persist persistReducer() function.

Without being fully proficient in redux-persist configuration/setup (again I am time constrained at the momemt), it seems to need two things:

1. wrap the top-level app-specific reducer with persistReducer()
2. inject PersistGate in your Root DOM

A very similar approach to your "wrapping" of feature-redux would be to simply "monkey patch" it with the needed hooks.  This technique may be somewhat "out of favor" but I think in this case it is much simpler.  Consider this:

```js
import React                 from 'react';
import {createReducerAspect} from 'feature-redux';
import {persistStore,
        persistReducer}      from 'redux-persist';
import {PersistGate}         from 'redux-persist/integration/react';
import storage               from 'redux-persist/lib/storage'; // defaults to localStorage for web

export function createPersistedReducerAspect(name='reducer') {

  // create the feature-redux Aspect to be patched
  const reducerAspect = createReducerAspect(name);

  // ... now apply necessary patches, in support of redux-persist

  // patch createReduxStore$(appReducer, middlewareArr)
  // NOTE: This is an "undocumented" method allowing a client user to 
  //       override and/or patch the redux createStore() functionality :-)
  const original_createReduxStore$ = reducerAspect.config.createReduxStore$;
  reducerAspect.config.createReduxStore$ = (appReducer, middlewareArr) => {

    // wrap our top-level app-specific reducer with redux-persist persistReducer()
    // NOTE: This could even be a parameter to our Aspect
    const persistConfig = {
      key: 'root',
      storage,
    };
    const persistedAppReducer = persistReducer(persistConfig, appReducer);

    // invoke the original function with our "wrapped" appReducer
    original_createReduxStore$(persistedAppReducer, middlewareArr);
  }

  // patch injectRootAppElm(fassets, curRootAppElm)
  // to inject PersistGate in our Root DOM
  const original_injectRootAppElm = reducerAspect.injectRootAppElm;
  reducerAspect.injectRootAppElm = (fassets, curRootAppElm) => {

    const persistor = persistStore(reducerAspect.getReduxStore());

    // invoke the original function after injecting PersistGate
    return original_injectRootAppElm(fassets,
                                     <PersistGate loading={null} persistor={persistor}>{curRootAppElm}</PersistGate>);
  }

  // that's all folks :-)
  return reducerAspect;
}
```

Let me know if this helps.

</Kevin>

**Comment by slgarkea** [comment]
It's helping, thanks.
I will publish the module as soon as possible.

----

I start with the code above and explain - below - every step in order to make it work properly.

### 1 - monorepo issue - lerna

I had a scope issue with the `validAspectProps`.
The module `feature-redux` configure `getReduxStore` & `getReduxMiddleware` in the right way but `launchApp` wasn't able to retrieve them.

It turns out, i have `feature-u` and `feature-redux` as `devDependencies` in `feature-redux-persist` module and as `dependencies` in my main app module.

After change `devDependencies` to `peerDependencies`, the error was gone.

So, be careful, ensure there is only one `feature-u` dependency to your entire project.

Error :

![Simulator Screen Shot - iPhone X - 2019-12-18 at 12 18 28](https://user-images.githubusercontent.com/16131914/71082059-bbeb7900-2190-11ea-895b-e995a775e815.png)

### 2 - storage

Default storage for `redux-persist` cause crash on react-native application. The classic `localStorage` is not available on that platform.

I fix this by defining a mandatory `storage$` config. The control is made on `createReduxStore$` call.

```js
// In case of react (web) usage :
import storage from 'redux-persist/lib/storage'; // defaults to localStorage for web
// [...]
const reducerAspect = createPersistedReducerAspect();
reducerAspect.config.storage$ = storage
  

// In case of react-native (mobile) usage :
import AsyncStorage from '@react-native-community/async-storage';
// [...]
const reducerAspect = createPersistedReducerAspect();
reducerAspect.config.storage$ = AsyncStorage
```

### 3 - `this.reduxDevToolHook$()`

The call to the original `createReduxStore$` depends on `this.reduxDevToolHook$()`. The `this` context is broken in this case. I have to bind the correct context to the function is order to make it work.

By changing the way we declare the wrapping function, this work fine :

```js
reducerAspect.config.createReduxStore$ = (appReducer, middlewareArr) => {
```
become 
```js
reducerAspect.config.createReduxStore$ = function(appReducer, middlewareArr) {
```

For coherence, I modified the `injectRootAppElm` declaration in the same way. 

```js
reducerAspect.injectRootAppElm = function(fassets, curRootAppElm) {
```

> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

### 4 - lifecycle error - `appStore`

![Simulator Screen Shot - iPhone X - 2019-12-18 at 12 51 08](https://user-images.githubusercontent.com/16131914/71085556-176d3500-2198-11ea-98a6-c3b87ebaa663.png)

It seem to be a scope problem.
The `this.appStore` is not read in the right object, the `this` reference seem wrong.

By binding the `reducerAspect` to the original `injectRootAppElm`, the module start and work 🚀 

```js
const original_injectRootAppElm = reducerAspect.injectRootAppElm.bind(
  reducerAspect
);
```

### Questions

In the documentation, I understand that you can aggregate some redux middleware by defining `getReduxMiddleware` in your `createAspect` definition.

Is it possible to override `getReduxStore` behaviour by this way ?

**Comment by KevinAst** [comment]
I am happy to hear it is working for you.

Sorry about the binding issues of my arrow functions.  This is one of those iterative things that you realize in usage _(however I should have caught this from the start)_.

That was a good catch on the binding of `original_injectRootAppElm`.  **My bad AGAIN!** This could also be addressed by altering how it is invoked:

```
FROM:  return original_injectRootAppElm(fassets, ...);
TO:    return reducerAspect.original_injectRootAppElm(fassets, ...);
```

Regarding your question, the `getReduxMiddleware()` is something you would invoke, not override.  You can see this in action in the [feature-redux-logic](https://github.com/KevinAst/feature-redux-logic) Aspect Plugin.

I am unsure what you are asking regarding `getReduxStore()` but I suspect any type of manipulation to the store would require an enhancement to the plugin.

**Question on redux-persist**:

I dreamed about this last night ... is it correct that you typically only wrap sub-sections of your state with `persistReducer()`?  That would make sense to me.  **If so**, then this is something you would do in your appropriate `Feature.reducer` feature-based state slices, **not** in the Aspect itself.

I'm glad you are **up-and-running**!

**Comment by slgarkea** [comment]
> Question on redux-persist:

> I dreamed about this last night ... is it correct that you typically only wrap sub-sections of your state with persistReducer()? That would make sense to me. If so, then this is something you would do in your appropriate Feature.reducer feature-based state slices, not in the Aspect itself.

I have both in my current project, root `persistReducer()` with `whitelist` configuration - which enable persistance for the listed reducers - and many sub-reducer with custom configuration when I don't want to persist all fields.

I have in mind to remove the root configuration in order to let features handle that configuration for themselves. I think this is much more in the feature-u's way of thinking.

**Comment by KevinAst** [comment]
I think I would agree with that "feature philosophy".

In that mindset, your `feature-redux-persist` plugin could stand on it's own, and **NOT** patch the `feature-redux` plugin.  All it has to do is implement `injectRootAppElm()` to inject the PersistGate DOM.

It would need to do a minor bit of [Aspect Cross Communication](https://feature-u.js.org/cur/extending.html#aspect-cross-communication) (via the `assembleAspectResources()` hook), in order to access the redux store.

That way, your project would include BOTH of these Aspect Plugins:
- `feature-redux`
- `feature-redux-persist`

Thoughts?

**Comment by sylvainlg** [comment]
I'm ok with that.

I rewrote the module based on your suggestions. You can find it on https://github.com/sylvainlg/feature-redux-persist.

**Comment by KevinAst** [comment]
Very nice.  I think this is a much improved design for this aspect plugin!

If you are interested here are a couple of observations (regarding the implementation):

1. A more robust way of detecting feature-redux would be to look for a plugin aspect containing the `getReduxStore` method.  The current technique looks for a name of 'reducer', which can vary based on usage.  Along the same line, the local variable could be renamed to reduxAspect (very minor).

2. VERY MINOR: This aspect plugin should probably not even accept a name parameter ... rather just hard-code it to something that indicates it will never be used (ex: 'unusedNamePersistedReducer').  Technically, after seeing this use case, I should probably enhance feature-u `createAspect()` to make name completely optional, when it is not needed.

3. Interesting technique to detect order dependency (in that the redux aspect's getReduxStore() will throw an error in that scenario).  It's always nice when you can detect this issue and pro-actively inform the user.

4. Wow: you are injecting persistReducer in the app root reducer.  I'm not up-to-speed enough with redux-persist, but is that always needed when you do this at feature slice level?  At any rate, it is kool that you have that hook.

Over all, very nice work ... I'm impressed :-)

**SideBar**: Within your app's mainline startup process, I am now using a simplified technique to promote the Aspects. I promote an `aspects/` directory, with an `aspects/index.js` which allows your aspects to be promoted through a single import.  This makes your `app.js` mainline extremely simple.

You can see an example of this in [Aspect Accumulation](https://feature-u.js.org/cur/usage.html#aspect-accumulation).

This is a similar pattern to how features are accumulated.  The main difference between `aspects/index.js` (vs. `features/index.js`) is that aspects are typically pulling/configuring resources from external NPM packages, rather than locally defined within the project.  With that said it provides a place for local aspects, should you need them.

**Comment by KevinAst** [comment]
One additional thing I dreamed about last night ... I do my best work in my sleep :-)

That is: There is no reason that your configuration can't be supplied up-front in your pseudo constructor ... for example:

```
+ createPersistedReducerAspect(storage): Aspect
```

You can take this with a grain of salt, but I think this provides a better user experience, by allowing them to avoid a multi-step process in their usage.  In addition, you can implement your configuration validation right in your pseudo constructor.

This is actually a TODO _(on my part)_ to update the **feature-u** extension docs and retrofit one of my promoted plugin aspects.  However I didn't want this current "status quo" to necessarily be extended into new plugin Aspects _(such as yours)_.

**Background**

<ul>

Originally, I promoted my plugin Aspects directly as pre-carved-out singleton objects.  That required a technique where the configuration had to be patched in after instantiation.  I later decided that singleton objects wasn't a good idea, and started promoting the pseudo constructor function (e.g. `createXyzAspect(...)`).  In my **single focused mindset** I neglected to realize that configuration would be better applied as parameters to the `create` function.

I have no plans for **feature-u** to change the `Aspect.config` sub-object, however I think it is better to consider it an _internal detail_ and not expose it to the user directly.

Thoughts?

</ul>

**SideBar**

<ul>

I also wanted to mention that I have recently promoted a [**feature-u** video presentation](https://feature-u.js.org/2.1.1/presentation.html).  I suspect you are very familiar with all **feature-u** concepts _because you are actually writing plugins for it_, however it might be worth a quick review.  Concepts like the dynamic plug-and-play are hard to convey without actually seeing it in action.

At any rate, I would be interested in your feedback, if you have time :-)

In general, I am using this [Teaser Article](http://bit.ly/feature-u-teaser) to introduce **feature-u** concepts.  It has a "Learning More" section at the end with reference links to important starter references.

</ul>

Thanks for being a **feature-u** user and contributor!

**PS**: You can reach me directly at kevin@wiiBridges.com

**Comment by sylvainlg** [comment]
**On the `feature-redux-persist` aspect implementation**

1/ I made the change on feautre-redux aspect detection : https://github.com/sylvainlg/feature-redux-persist/pull/1

4/ The root reducer must be `redux-persist`ed, in the oposite case the app don't start (white screen on react-native app)

I will take a look at `aspects/index.js`.

**named aspects**

```js
+ createPersistedReducerAspect(storage): Aspect
```

I asked me the very same question about passing configuration through constructor rather than later configuration. I didn't do it because existing aspects don't work like that.
So i couldn't agree more.

My point was, how to keep the optionnal `name` parameter in a consistant API (first param is great) for every aspects and put some mandatory parameter after it, which is not a good practice (mandatories first, optionnals then).

But if there are named and unamed aspects, the question may be irrelevant.

**documentation & support**

I will take a look at the video when I make feature-u presentation for my team (during january).

--

feature-u is the only modularization module, which deserve that name, i'm found in the React world. It's a really good piece of software and well documented ! I hope we can take it to production.

**Comment by KevinAst** [comment]
**createPersistedReduxAspect API**

Regarding parameter order, when this becomes an issue for me, I typically like to use "named" parameters.  In many cases this makes the API much more explicit.  In another post you mentioned the redux `connect()` function.  When using this function I am always passing in undefined/null to reach a needed positional parameter.  I always **wrap** this function with one that uses named parameters ... see: [`withState()`](https://github.com/KevinAst/eatery-nod-w/blob/master/src/util/withState.js)

In your specific case, the `name` parameter is **never** needed because you are **not** gathering any aspect resources from your features.  Remember, the Aspect Plugin `name` extends `Feature` to allow that named property to be specified in your feature objects.  Your use case is a new one for me to consider, and something I should relax in `createAspect()` (my TODO to make `name` optional ... as well as `validateFeatureContent()` and `assembleFeatureContent`).

In terms of a "consistent" API for all Aspect plugins, I'm not sure that is really necessary.  I think each Aspect plugin has the potential of using a unique API specific to it's needs.

I would see your Aspect's API being:

```
+ createPersistedReduxAspect(storage): Aspect
```

**Merci**

Thanks for the **feature-u** complement :-)

BTW, I am retired, so I could do a presentation to your group for only travel expenses for two (i.e. my wife included) ... just kidding, but it would be fun _(however I do not speak French :-)_
